apiVersion: v1
kind: Service
metadata:
  name: nhi-alps-backend
  namespace: nhi-alps
spec:
  selector:
    app: nhi-alps-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4000
  type: ClusterIP
