import type { UserRole, RBACAction } from '@/types/user.types'

const RBAC: Record<UserRole, RBACAction[]> = {
  L0: [
    'VIEW_INVENTORY', 'CREATE_NHI_REQUEST', 'APPROVE_REQUEST', 'MANAGE_CONNECTORS',
    'TRIGGER_DISCOVERY', 'VIEW_POSTURE', 'REMEDIATE_ISSUE', 'VIEW_ALERTS',
    'DISMISS_ALERT', 'ESCALATE_ALERT', 'TRIGGER_ROTATION', 'VIEW_COMPLIANCE',
    'EXPORT_COMPLIANCE', 'MANAGE_CAMPAIGNS', 'SUBMIT_CERTIFICATION', 'VIEW_AUDIT_LOG',
    'MANAGE_USERS', 'SYSTEM_CONFIG', 'VIEW_VAULT',
  ],
  L1: [
    'VIEW_INVENTORY', 'CREATE_NHI_REQUEST', 'APPROVE_REQUEST',
    'TRIGGER_DISCOVERY', 'VIEW_POSTURE', 'REMEDIATE_ISSUE', 'VIEW_ALERTS',
    'DISMISS_ALERT', 'ESCALATE_ALERT', 'TRIGGER_ROTATION', 'VIEW_COMPLIANCE',
    'EXPORT_COMPLIANCE', 'MANAGE_CAMPAIGNS', 'SUBMIT_CERTIFICATION', 'VIEW_AUDIT_LOG',
  ],
  L2: [
    'VIEW_INVENTORY', 'TRIGGER_DISCOVERY', 'VIEW_POSTURE', 'REMEDIATE_ISSUE',
    'VIEW_ALERTS', 'DISMISS_ALERT', 'ESCALATE_ALERT', 'TRIGGER_ROTATION',
    'VIEW_AUDIT_LOG',
  ],
  L3: [
    'VIEW_INVENTORY', 'CREATE_NHI_REQUEST',
  ],
  L4: [
    'VIEW_INVENTORY', 'VIEW_POSTURE', 'VIEW_ALERTS', 'VIEW_COMPLIANCE',
    'EXPORT_COMPLIANCE', 'SUBMIT_CERTIFICATION', 'VIEW_AUDIT_LOG',
  ],
  L5: [
    'VIEW_INVENTORY', 'VIEW_POSTURE',
  ],
}

export function hasPermission(role: UserRole, action: RBACAction): boolean {
  return RBAC[role]?.includes(action) ?? false
}

export function getRolePermissions(role: UserRole): RBACAction[] {
  return RBAC[role] ?? []
}
